# Generated by Django 5.2.6 on 2025-10-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_prods_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prods',
            new_name='products',
        ),
    ]
