# Generated by Django 5.2.6 on 2025-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(max_length=10, unique=True)),
                ('empcon', models.IntegerField(max_length=13, unique=True)),
                ('empname', models.CharField(max_length=15)),
                ('empdep', models.CharField(max_length=40)),
                ('empemail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
