# Generated by Django 5.2.6 on 2025-10-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(unique=True)),
                ('owner_name', models.CharField(max_length=50)),
            ],
        ),
    ]
