# Generated by Django 5.2.6 on 2025-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owned',
            name='products',
            field=models.CharField(default='empty', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='owned',
            name='owner_id',
            field=models.IntegerField(),
        ),
    ]
