# Generated by Django 5.2.6 on 2025-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0002_owned_products_alter_owned_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owned',
            name='products',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
