# Generated by Django 5.2.6 on 2025-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0004_remove_owned_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owned',
            name='owner_id',
            field=models.IntegerField(default='0000'),
        ),
    ]
