# Generated by Django 5.2.6 on 2025-10-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0006_alter_owned_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='products',
        ),
    ]
