# Generated by Django 5.2.6 on 2025-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0007_remove_owned_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owned',
            name='owner_id',
            field=models.IntegerField(unique=True),
        ),
    ]
