# Generated by Django 5.2.6 on 2025-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0008_alter_owned_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owned',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
