# Generated by Django 5.2.6 on 2025-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0009_alter_owned_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owned',
            name='products',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
