# Generated by Django 5.2.6 on 2025-10-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0010_owned_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='owned',
            name='products',
        ),
    ]
