# Generated by Django 5.2.6 on 2025-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0011_remove_owned_owner_id_remove_owned_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='owned',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owned',
            name='products',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
