# Generated by Django 5.2.6 on 2025-10-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0012_remove_owned_owner_name_owned_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='owned',
            name='products',
        ),
    ]
