# Generated by Django 5.2.6 on 2025-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0013_remove_owned_owner_id_remove_owned_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='owned',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owned',
            name='owner_name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='owned',
            name='products',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
