# Generated by Django 5.2.6 on 2025-10-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0014_owned_owner_id_owned_owner_name_owned_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='owned',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='owned',
            name='products',
        ),
        migrations.AddField(
            model_name='owned',
            name='product_name',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
