# Generated by Django 5.2.6 on 2025-10-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0015_remove_owned_owner_id_remove_owned_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='product_name',
        ),
    ]
