# Generated by Django 5.2.6 on 2025-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owned', '0016_remove_owned_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='owned_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=20)),
                ('products', models.CharField(default='empty', max_length=100)),
                ('owner_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='owned',
        ),
    ]
